# generated by penchant, environment: remote, deployment mode (was remote)
source "https://rubygems.org"
gem "rails", "3.2.9"
gem "sqlite3"

group :assets do
  gem "sass-rails", "~> 3.2.3"
  gem "coffee-rails", "~> 3.2.1"
  gem "uglifier", ">= 1.0.3"
end
gem "haml"
gem "haml-rails"
gem "compass"
gem "compass-rails"
gem "jquery-rails"
gem "pjax_rails", {:git=>"git://github.com/maletor/pjax_rails.git"}
gem "modernizr-rails"
gem "thin"
gem "rack-emstream"
gem "rabl"
gem "param_protected"
gem "draper"
gem "inherited_resources"
gem "decorates_before_rendering"
gem "capistrano", {:require=>nil}
gem "cap-pack", {:git=>"git://github.com/johnbintz/cap-pack.git", :require=>nil}
gem "formtastic"
gem "formtastic-better_file_inputs", {:git=>"git://github.com/johnbintz/formtastic-better_file_inputs"}
gem "cocoon", {:branch=>"formtastic_input", :git=>"git://github.com/johnbintz/cocoon.git"}
gem "virtus"

group :development do
  gem "rack-livereload"
  gem "guard"
  gem "guard-livereload"
  gem "guard-cucumber"
  gem "foreman"
end

group :test, :development, :cucumber do
  gem "rspec"
end

group :cucumber do
  gem "cucumber"
  gem "cucumber-rails"
  gem "database_cleaner"
  gem "cuke-pack", {:git=>"git://github.com/johnbintz/cuke-pack.git"}
end